version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  backend-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: backend-worker
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
