version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads  # ensure uploaded images persist

  worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info -Q image_queue
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
