version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - maxflow-network

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - maxflow-network
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: ./backend
    restart: unless-stopped
    command: celery -A app.celery_app.celery_app worker --loglevel=info -Q image_queue
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - maxflow-network
    volumes:
      - ./backend:/app

  flower:
    image: mher/flower
    restart: unless-stopped
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=admin:adminpass
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - maxflow-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - maxflow-network
    volumes:
      - ./frontend:/app
    command: npm run start

networks:
  maxflow-network:
    driver: bridge
