version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - maxflow-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - maxflow-network
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A app.celery_app.celery_app worker --loglevel=info -Q image_queue
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend
    networks:
      - maxflow-network
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - maxflow-network
    volumes:
      - ./frontend:/app
    command: npm run dev

networks:
  maxflow-network:
    driver: bridge
