version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    networks:
      - shopify-ai-network
    depends_on:
      - ai-service

  ai-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./ai-service:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - shopify-ai-network
    depends_on:
      - redis

  ai-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    command: celery -A main worker --loglevel=info
    volumes:
      - ./ai-service:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - shopify-ai-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - shopify-ai-network

  flower:
    image: mher/flower:1.2
    command: celery flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    networks:
      - shopify-ai-network
    depends_on:
      - redis
      - ai-worker

networks:
  shopify-ai-network:
    driver: bridge

volumes:
  redis-data: 