version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build: ./backend
    command: celery -A celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
