name = "Maxflow AI Image App"
client_id = "39e28007c7d0d65a26cc66cef72fa7c2"
application_url = "https://5f03-103-244-174-250.ngrok-free.app"
embedded = true
scope = "read_products, write_products"

[auth]
redirect_urls = [
  "https://5f03-103-244-174-250.ngrok-free.app/api/auth/callback"
]

[web]
application_url = "https://5f03-103-244-174-250.ngrok-free.app"
socket = "3000"

[build]
command = "npm run build"

[develop]
command = "npm run dev"
port = 3000
tunnel = true

[webhooks]
api_version = "2023-07"
subscriptions = [
  { topics = ["APP_UNINSTALLED"], path = "/api/webhooks", uri = "https://5f03-103-244-174-250.ngrok-free.app/api/webhooks" }
]
