name = "Maxflow AI Image App"
client_id = "39e28007c7d0d65a26cc66cef72fa7c2"
application_url = "https://b4ec-2400-adc1-47c-4e00-196c-765e-ee46-c49f.ngrok-free.app"
embedded = true
scope = "read_products, write_products"

[auth]
redirect_urls = [
  "https://b4ec-2400-adc1-47c-4e00-196c-765e-ee46-c49f.ngrok-free.app/api/auth/callback"
]

[web]
application_url = "https://b4ec-2400-adc1-47c-4e00-196c-765e-ee46-c49f.ngrok-free.app "
socket = "3000"

[build]
command = "npm run build"

[develop]
command = "npm run dev"
port = 3000
tunnel = true

[webhooks]
api_version = "2023-07"
subscriptions = [
  { topics = ["APP_UNINSTALLED"], path = "/api/webhooks", uri = "https://b4ec-2400-adc1-47c-4e00-196c-765e-ee46-c49f.ngrok-free.app/api/webhooks" }
]
